version: '3'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Q1x2v4c5
      MYSQL_DATABASE: octopus
      MYSQL_USER: octotest
      MYSQL_PASSWORD: Q1x2v4c5
    #ports:
    # - "3306:3306"
  web:
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--timeout=60", "--", "python3", "main.py"]
    ports:
     - "8888:8888"
    links:
     - db
    depends_on:
     - db
